"""Constants for the PoolOS Home Assistant integration."""

from __future__ import annotations

from datetime import timedelta

DOMAIN = "poolos"
NAME = "PoolOS"
INTEGRATION_VERSION = "0.4.0"

CONF_DIAGNOSTICS_ENABLED = "diagnostics_enabled"
DEFAULT_DIAGNOSTICS_ENABLED = True

CONF_POOL_ACTIVE_ENTITY = "pool_active_entity"
CONF_SPA_ACTIVE_ENTITY = "spa_active_entity"
CONF_PUMP_RPM_ENTITY = "pump_rpm_entity"
CONF_POOL_TEMPERATURE_ENTITY = "pool_temperature_entity"
CONF_SPA_TEMPERATURE_ENTITY = "spa_temperature_entity"
CONF_HEATER_ACTIVE_ENTITY = "heater_active_entity"
CONF_SOLAR_ACTIVE_ENTITY = "solar_active_entity"
CONF_PUMP_POWER_ENTITY = "pump_power_entity"

REQUIRED_ENTITY_OPTIONS = (
    CONF_POOL_ACTIVE_ENTITY,
    CONF_SPA_ACTIVE_ENTITY,
    CONF_PUMP_RPM_ENTITY,
    CONF_POOL_TEMPERATURE_ENTITY,
    CONF_SPA_TEMPERATURE_ENTITY,
)
OPTIONAL_ENTITY_OPTIONS = (
    CONF_HEATER_ACTIVE_ENTITY,
    CONF_SOLAR_ACTIVE_ENTITY,
    CONF_PUMP_POWER_ENTITY,
)
ALL_ENTITY_OPTIONS = REQUIRED_ENTITY_OPTIONS + OPTIONAL_ENTITY_OPTIONS

OBSERVATION_UPDATE_INTERVAL = timedelta(seconds=30)
OBSERVATION_STALE_AFTER = timedelta(minutes=5)

OPERATING_MODE_OBSERVE = "OBSERVE"
DEFAULT_OPERATING_MODE = OPERATING_MODE_OBSERVE

PLATFORMS = ("sensor",)
